---
version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  version: 2

  setup:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/continue-config.yml
          mapping: |
            ^((?!docs$).)*$ trigger-src true
            ^docs$ trigger-docs true
