---
version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.0.2

executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.05

parameters:
  trigger-src:
    type: boolean
    default: false
  trigger-docs:
    type: boolean
    default: false

workflows:
  version: 2
  
  build-src:
    when: << pipeline.parameters.trigger-src >>
    jobs:
      - build-from-source

  build-docs:
    when: << pipeline.parameters.trigger-docs >>
    jobs:
      - generate-docs

jobs:
  build-from-source:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build from source
          command: |
            echo "... build from source"

  generate-docs:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Generate docs from source
          command: |
            echo "... generate docs"
